version: '3'
services:
  app:
    image: ghcr.io/dotoleeoak/military-in
    container_name: military-in-app
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/app:/data
    environment:
      - POSTGRES_DB=bulgogi
      - POSTGRES_USER=bulgogi
      - POSTGRES_PASSWORD=bulgogi
      - DATABASE_URL=postgres://bulgogi:bulgogi@localhost:5432/bulgogi
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  db:
    image: postgres:12-alpine
    container_name: military-in-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bulgogi
      - POSTGRES_USER=bulgogi
      - POSTGRES_PASSWORD=bulgogi
